### ISSUE TITLE
[Tracking] More Commands

### ISSUE THREAD

**Issue by felix-andreas** [tiny-technologies/neural#11]
follow up to #10 

- train
  - [x] `-c --checkpoint` path to existing network #27 
- run
  - [x] <path/to/network> <path/to/input> #29 
- [x] bench -> (print runtime for forward pass and backward pass individually) #16
